---
title: "R Notebook"
output: html_notebook
---

```{r}
#required libraries
library(ggplot2)
library(dplyr)
library(reshape2)
install.packages("coin")
library(coin)
library(irr)
```
```{r}
data <- read.table("order_study_data.csv", sep=",", header=TRUE)
head(data)
```

```{r}
data <- group_by(data, condition)
aggregate <- summarise(data,
                       n = length(condition),
                         #mean ratings
                       med_total_orig = median(sum_orig),   
                       avg_total_orig = mean(sum_orig),
                          sd_total_orig = sd(sum_orig),
                          se_total_orig = sd_total_orig/sqrt(length(condition)),
                      med_avg_orig = median(sum_orig),   
                       avg_orig = mean(orig),
                          sd_avg_orig = sd(orig),
                          se_avg_orig = sd_avg_orig/sqrt(length(condition)),
                       med_total_util = median(sum_util),
                          avg_total_util = mean(sum_util),
                          sd_total_util = sd(sum_util),
                          se_total_util = sd_total_util/sqrt(length(condition)),
                       med_avg_util = median(util),   
                       avg_util = mean(util),
                          sd_avg_util = sd(util),
                          se_avg_util = sd_avg_util/sqrt(length(condition)),
                      sum = mean(sum_total),
                      sd_sum = sd(sum_total),
                      se_sum = sd_sum/sqrt(length(condition)))

aggregate
```
```{r}
#originality histograms

#***t1
ggplot(data, aes(x=orig_t1,color=condition))+
  geom_histogram(alpha=0.5, position="dodge", binwidth=.5)+
  scale_color_manual(values=c("blue","green"))

#***t2
ggplot(data, aes(x=orig_t2,color=condition))+
  geom_histogram(alpha=0.5, position="dodge", binwidth=.5)+
  scale_color_manual(values=c("blue","green"))
```
```{r}
#utility histograms
ggplot(data, aes(x=util_t1,color=condition))+
  geom_histogram(alpha=0.5, position="dodge", binwidth=.5)+
  scale_color_manual(values=c("blue","green"))

ggplot(data, aes(x=util_t2,color=condition))+
  geom_histogram(alpha=0.5, position="dodge", binwidth=.5)+
  scale_color_manual(values=c("blue","green"))
```


```{r}
time <- summarise(data,
                  #diff
                  avg_orig_diff = mean(diff_orig),
                  sd_orig_diff = sd(diff_orig),
                  se_orig_diff = sd(diff_orig)/sqrt(length(condition)),
                  avg_util_diff = mean(diff_util),
                  sd_util_diff = sd(diff_util),
                  se_util_diff = sd(diff_util)/sqrt(length(condition)),
                  #first design
                  med_orig_t1 = median(orig_t1),
                  avg_orig_t1 = mean(orig_t1),
                  sd_orig_t1 = sd(orig_t1),
                  se_orig_t1 = sd_orig_t1/sqrt(length(condition)),
                  med_util_t1 = median(util_t1),
                  avg_util_t1 = mean(util_t1),
                  sd_util_t1 = sd(util_t1),
                  se_util_t1 = sd_util_t1/sqrt(length(condition)),
                  mean_sum_t1 = mean(sum_t1),
                  sd_sum_t1 = sd(sum_t1),
                  se_sum_t1 = sd_sum_t1/sqrt(length(condition)),
                  #second design
                  med_orig_t2 = median(orig_t2),
                  avg_orig_t2 = mean(orig_t2),
                  sd_orig_t2 = sd(orig_t2),
                  se_orig_t2 = sd_orig_t2/sqrt(length(condition)),
                  med_util_t2 = median(util_t2),
                  avg_util_t2 = mean(util_t2),
                  sd_util_t2 = sd(util_t2),
                  se_util_t2 = sd_util_t2/sqrt(length(condition)),
                  mean_sum_t2 = mean(sum_t2),
                  sd_sum_t2 = sd(sum_t2),
                  se_sum_t2 = sd_sum_t2/sqrt(length(condition))
                  )

time
```

```{r}
irr <- read.table("irr_order.csv",sep=",",header=TRUE)
irr <- as.matrix(irr)

kappa2(irr, "equal")
```

```{r}
#filter data into conditions
explore_first <- data %>%
  filter(condition=="Explore")

exploit_first <- data %>%
  filter(condition=="Exploit")
```
```{r}
#repeated measures paired t-tests for originality between designs
t.test(explore_first$orig_t2,explore_first$orig_t1, paired=TRUE)
t.test(exploit_first$orig_t2,exploit_first$orig_t1, paired=TRUE)
```
```{r}
#repeated measures paired t-tests for utility between designs
t.test(explore_first$util_t2,explore_first$util_t1, paired=TRUE)
t.test(exploit_first$util_t2,exploit_first$util_t1, paired=TRUE)
```

```{r}
explore_orig <- lm(orig_t2 - orig_t1 ~ pid, data=explore_first)
summary(explore_orig)

exploit_orig <- lm(orig_t2 - orig_t1 ~ pid, data=exploit_first)
summary(exploit_orig)
```

```{r}
orig_diff <- lm(diff_orig ~ condition + (1 | pid), data=data)
summary(orig_diff)

util_diff <- lm(diff_util ~ condition + (1 | pid), data=data)
summary(util_diff)
```
```{r}
#boxplot
ggplot(data, aes(x=condition, y=orig_t1, fill=condition)) +
  #stat_boxplot(geom='errorbar',width=.5)+
  geom_boxplot(width=.3) +
  theme_bw() +
  scale_fill_manual(values=c("lightskyblue2","palegreen3")) +
  scale_y_continuous(name="Average Rating") +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        panel.border = element_blank(),
        axis.line = element_line(colour = "black"),
        text = element_text(size=20))
```
```{r}
ggplot(data, aes(x=condition, y=orig_t2, fill=condition)) +
 # stat_boxplot(geom='errorbar',width=.5)+
  geom_boxplot(width=.3) +
  theme_bw() +
  scale_fill_manual(values=c("dodgerblue2","green4")) +
  scale_y_continuous(name="Average Rating") +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        panel.border = element_blank(),
        axis.line = element_line(colour = "black"),
        text = element_text(size=20))
```

```{r}
ggplot(data, aes(x=condition, y=util_t1, fill=condition)) +
  geom_boxplot(width=.3) +
  theme_bw() +
  scale_fill_manual(values=c("lightskyblue2","palegreen3")) +
  scale_y_continuous(name="Average Rating") +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        panel.border = element_blank(),
        axis.line = element_line(colour = "black"),
        text = element_text(size=20))
```
```{r}
ggplot(data, aes(x=condition, y=util_t2, fill=condition)) +
  geom_boxplot(width=.3) +
  theme_bw() +
  scale_fill_manual(values=c("dodgerblue2","green4")) +
  scale_y_continuous(name="Average Rating") +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        panel.border = element_blank(),
        axis.line = element_line(colour = "black"),
        text = element_text(size=20))
```

```{r}
orig_t1 <- lm(orig_t1 ~ condition + (1 | pid), data=data)
summary(orig_t1)

orig_t2 <- lm(orig_t2 ~ condition + (1 | pid), data=data)
summary(orig_t2)
```


```{r}
util_t1 <- lm(util_t1 ~ condition + (1 | pid), data=data)
summary(util_t1)

util_t2 <- lm(util_t2 ~ condition + (1 | pid), data=data)
summary(util_t2)
```
```

```{r}
#power analysis for follow up study
pwr.anova.test(k=5,f=.4,sig.level=.05,power=.8)
```

