---
title: "R Notebook"
output: html_notebook
---


```{r}
#required libraries
library(ggplot2)
#library(car)
library(dplyr)
#library(reshape2)
#library(pwr)
install.packages("irr")
library(irr)
library(coin)
```
```{r}
baseline <- read.table("baseline_data.csv", sep=",", header=TRUE)
head(baseline)
```
```{r}
baseline <- group_by(baseline, condition)
baseline_summary <- summarise(baseline,
                              orig = mean(final_orig),
                              sd_orig = sd(final_orig),
                              se_orig = sd_orig/sqrt(length(condition)),
                              util = mean(final_prac),
                              sd_util = sd(final_prac),
                              se_util = sd_util/sqrt(length(condition)),
                              diff = mean(difference),
                              sd_diff = sd(difference),
                              se_diff = sd_diff/sqrt(length(condition)))

baseline_summary
```
```{r}
#inter-rater reliability
irr <- read.table("irr_baseline.csv", sep=",", header=TRUE)
irr <- as.matrix(irr)

irr_diff <- read.table("irr_difference.csv", sep=",", header=TRUE)
irr_diff <- as.matrix(irr_diff)

kappa2(irr,"equal")
kappa2(irr_diff,"equal")
```
```{r}
#wilcoxon rank tests
orig <- wilcox.test(baseline$final_orig~baseline$condition)
util <- wilcox.test(baseline$final_prac~baseline$condition)
difference <- wilcox.test(baseline$difference~baseline$condition)

orig
util
difference
```

```{r}
orig <- lm(final_orig ~ condition + (1 | pid), data=baseline)
summary(orig)

util <- lm(final_prac ~ condition + (1 | pid), data=baseline)
summary(util)
```

```{r}
#boxplot
ggplot(baseline, aes(x=condition, y=final_orig, fill=condition)) +
  geom_boxplot() +
  scale_fill_manual(values=c("dodgerblue2","green4")) +
  scale_y_continuous(name="Average Rating") +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        panel.border = element_blank(),
        axis.line = element_line(colour = "black"),
        text = element_text(size=20))
```
```{r}
ggplot(baseline, aes(x=condition, y=final_prac, fill=condition)) +
  geom_boxplot() +
  scale_fill_manual(values=c("dodgerblue2","green4")) +
  scale_y_continuous(name="Average Rating") +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        panel.border = element_blank(),
        axis.line = element_line(colour = "black"),
        text = element_text(size=20))
```

```{r}
ggplot(baseline_summary, aes(x=condition, y=diff, fill=condition)) +
  geom_bar(stat="identity", position=position_dodge()) +
  #geom_boxplot()+
  geom_errorbar(aes(ymin=diff-se_diff, ymax=diff+se_diff), width=.2) +
  scale_fill_manual(values=c("dodgerblue2","green4")) +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        panel.border = element_blank(),
        axis.line = element_line(colour = "black"),
        text = element_text(size=20))
```

```{r}
diff <- lm(difference ~ condition + (1|pid), data=baseline)
summary(diff)
```

